# This workflow will install Python dependencies, run and update hw-apartment.db  

name: Daily Run

on:
  # workflow_dispatch:
  # 北京时间上午8点更新
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      run: |
        python main.py ${{ secrets.UID }} ${{ secrets.PASSWORD }}
    - name: Sync then display
      run: |
        git config --global user.email "gaoyunfeng1995@gmail.com"
        git config --global user.name "YunfengGao"
        git commit -am 'sync today data then diplay'
        git push
