# This workflow will install Python dependencies, run and update hw-apartment.db  

name: Daily Run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      run: |
        python main.py ${{ secrets.UID }} ${{ secrets.PASSWORD }}
    - name: Update hw-apartment.db
      run: |
        git config --global user.email "gaoyunfeng1995@gmail.com"
        git config --global user.name "YunfengGao"
        git commit -am 'update hw-apartment.db'
        git push
